// <auto-generated />
namespace Tarefas.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IniciodoProjeto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IniciodoProjeto));
        
        string IMigrationMetadata.Id
        {
            get { return "201706210144113_Inicio do Projeto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
